### ISSUE TITLE
Zero bytes in `data` paramater `Radamsa.fuzz` seem to cause very limited mutations

### ISSUE THREAD

**Issue by quapka** [tsundokul/pyradamsa#1]
As far as I understand fuzzing techniques, each _almost_ each fuzzing should produce a new value (repetition is of a little use). However, I've come across scenario, where only few output values are produces. The problem seems to be in longer inputs with `0x00` bytes. I've created example script, that demonstrates this (_on my machine_).

```python
#!/usr/bin/env python
import sys
from pyradamsa import Radamsa

rad = Radamsa()
try:
    orig = bytes.fromhex(sys.argv[2])
except IndexError:
    orig = b"\xaa\x00"
orig = orig * 100

try:
    interations = int(sys.argv[1])
except IndexError:
    interations = 1000

fuzzed = []
for i in range(interations):
    fuzzed.append(rad.fuzz(orig))

print("%d fuzzings created %d unique values." % (interations, len(set(fuzzed))))
```

It simply calls `Radamsa.fuzz`for `iterations`-times and it fuzzes the `orig` string. The expected result:
```bash
$ python main.py 1000 aabb 
1000 fuzzings created 755 unique values.
```
This looks good, however, with zero byte:
```bash
$ python main.py 1000 aa00
1000 fuzzings created 39 unique values.
```
Am I missing something or is there a problem?

**Comment by tsundokul** [comment]
Thanks for reporting the issue, I'll investigate it in the following days

**Comment by tsundokul** [comment]
It turned out it was a bug indeed; the data was read by casting from a C string rather than reading back a number of fuzzed bytes, hence the returned data was truncated at first null byte

**Comment by quapka** [comment]
Yes, I was expecting that bug lurking in similar places. Thanks for the quick fix.
