### ISSUE TITLE
Output differs while using same seed on radamsa command line & pyradamsa

### ISSUE THREAD

**Issue by Fratso** [tsundokul/pyradamsa#2]
i.e:

```python
import subprocess
import pyradamsa


def mutate_cli(payload, seed):
    radamsa = ['/usr/bin/radamsa', '-n', '1', '-s', f'{seed}', '-']
    p = subprocess.Popen(radamsa, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    mutated_data = p.communicate(payload)[0]
    return mutated_data


def mutate_script(payload, seed):
    r = pyradamsa.Radamsa()
    mutatated_data = r.fuzz(payload, seed=seed)
    return mutatated_data


if __name__ == "__main__":
    s = 1337
    p = b"qwerty"
    output_cli = mutate_script(p, s)
    print(output_cli)
    output_script = mutate_cli(p, s)
    print(output_script)
    print("It's {} that mutations are equals".format(output_cli == output_script))

```

Output:

```
b'qwty'
b'qwe\xf3\xa0\x81\x82rty'
It's False that mutations are equals
```

I expected to obtain the same output by using the same seed

**Comment by tsundokul** [comment]
You are right, and that's what I stumbled upon when writing the bindings. I will quote the author of radamsa ([original issue](https://gitlab.com/akihe/radamsa/-/issues/72))

> The outputs really are different. Radamsa and libradamsa use the same mutation engine, but the startup is different. Same seeds don't lead to same outputs. It's roughly the same as starting radamsa with two different seeds.
> 
> Radamsa input is a chunk of memory. No encoding is necessary.
> 
> Many mutations will produce output that is printable if the input is, but not all of them. There is no way to limit changes to those that would preserve some specific encoding. If you want a printable mutation for example for documentation purposes, you could find a seed that happens to produce a suitable change.


I will update the README to reflect this aspect.
